// Filename:    game_objects.go
// Author:      Joseph DeVictoria
// Date:        Aug_30_2018

package shared

// Pc is a struct that contains all the information pertinent to a given player, name, health, mods etc...
type Pc struct {
	ID             int32
	AccountID      int32
	Firstname      string
	Lastname       string
	Guild          string
	Race           string
	Gender         string
	Face           string
	Skin           string
	Profession     string
	Alive          bool
	Plevel         int32
	Dp             int32
	Hp             int32
	Maxhp          int32
	Bp             int32
	Maxbp          int32
	Mp             int32
	Maxmp          int32
	Sp             int32
	Maxsp          int32
	Strength       int32
	Constitution   int32
	Intelligence   int32
	Dexterity      int32
	Axe            int32
	Dagger         int32
	Hammer         int32
	Polearm        int32
	Spear          int32
	Staff          int32
	Sword          int32
	Unarmed        int32
	Archery        int32
	Crossbow       int32
	Sling          int32
	Thrown         int32
	Armor          int32
	Dualweapon     int32
	Shield         int32
	Bardic         int32
	Conjuring      int32
	Druidic        int32
	Illusion       int32
	Necromancy     int32
	Shamanic       int32
	Sorcery        int32
	Summoning      int32
	Spellcraft     int32
	Focus          int32
	Alchemy        int32
	Armorsmithing  int32
	Calligraphy    int32
	Enchanting     int32
	Fletching      int32
	Lapidary       int32
	Tailoring      int32
	Weaponsmithing int32
	Herbalism      int32
	Hunting        int32
	Mining         int32
	Bargaining     int32
	Camping        int32
	Firstaid       int32
	Lore           int32
	Picklocks      int32
	Scouting       int32
	Search         int32
	Stealth        int32
	Traps          int32
	Aeolandis      int32
	Hieroform      int32
	Highgundis     int32
	Oldpraxic      int32
	Praxic         int32
	Runic          int32
	Head           string
	Chest          string
	Arms           string
	Hands          string
	Legs           string
	Feet           string
	Cloak          string
	Necklace       string
	Ringone        string
	Ringtwo        string
	Righthand      string
	Lefthand       string
	Zone           string
	X              float32
	Y              float32
	Z              float32
	Direction      float32
}

// SkillUpdate is a struct that allows you to specify all of the skills that the player is trying to spend development points on.
type SkillUpdate struct {
	Playername     string
	Predp          int32
	Spenddp        int32
	Strength       int32
	Constitution   int32
	Intelligence   int32
	Dexterity      int32
	Axe            int32
	Dagger         int32
	Hammer         int32
	Polearm        int32
	Spear          int32
	Staff          int32
	Sword          int32
	Unarmed        int32
	Archery        int32
	Crossbow       int32
	Sling          int32
	Thrown         int32
	Armor          int32
	Dualweapon     int32
	Shield         int32
	Bardic         int32
	Conjuring      int32
	Druidic        int32
	Illusion       int32
	Necromancy     int32
	Shamanic       int32
	Sorcery        int32
	Summoning      int32
	Spellcraft     int32
	Focus          int32
	Alchemy        int32
	Armorsmithing  int32
	Calligraphy    int32
	Enchanting     int32
	Lapidary       int32
	Tailoring      int32
	Fletching      int32
	Weaponsmithing int32
	Herbalism      int32
	Hunting        int32
	Mining         int32
	Bargaining     int32
	Camping        int32
	Firstaid       int32
	Lore           int32
	Picklocks      int32
	Scouting       int32
	Search         int32
	Stealth        int32
	Traps          int32
	Aeolandis      int32
	Hieroform      int32
	Highgundis     int32
	Oldpraxic      int32
	Praxic         int32
	Runic          int32
}

// Npc is a struct that contains all the information about an NPC that you would need in the game.
type Npc struct {
	ID           int32
	Firstname    string
	Lastname     string
	Guild        string
	Race         string
	Gender       string
	Face         string
	Skin         string
	Profession   string
	Alive        bool
	Nlevel       int32
	Hp           int32
	Maxhp        int32
	Bp           int32
	Maxbp        int32
	Mp           int32
	Maxmp        int32
	Sp           int32
	Maxsp        int32
	Strength     int32
	Constitution int32
	Intelligence int32
	Dexterity    int32
	Head         string
	Chest        string
	Arms         string
	Hands        string
	Legs         string
	Feet         string
	Cloak        string
	Righthand    string
	Lefthand     string
	Zone         string
	X            float32
	Y            float32
	Z            float32
	Direction    float32
}

// ItemTemplate is a struct that contains all of the relevant information about an item in game.
type ItemTemplate struct {
	ID                      int32
	Name                    string
	TrueName                string
	LoreLevel               int32
	ItemType                string
	Slot                    string
	Icon                    string
	Weight                  float32
	Encumbrance             float32
	Dyeable                 bool
	Stackable               bool
	StackSize               int32
	Usable                  bool
	Equipable               bool
	BasePrice               int32
	StrengthRequirement     int32
	ConstitutionRequirement int32
	IntelligenceRequirement int32
	DexterityRequirement    int32
	SkillType0              string
	SkillRequirement0       int32
	SkillType1              string
	SkillRequirement1       int32
	SkillType2              string
	SkillRequirement2       int32
	SkillType3              string
	SkillRequirement3       int32
	SkillType4              string
	SkillRequirement4       int32
	Description             string
	TrueDescription         string
}

// SpellTemplate is a struct that contains all of the information describing a given spell in the game.
type SpellTemplate struct {
	ID              int32
	Spellname       string
	School          string
	Level           int32
	Type            string
	Target          string
	Range           float32
	Accuracy        float32
	PreparationTime int32
	RecoveryTime    int32
	Effect1         string
	Effect2         string
	Effect3         string
	Effect4         string
	Effect5         string
	Description     string
}

// RaceTemplate is a struct that contains all of the information describing a given race in the game.  It contains all of the racial modifiers.
type RaceTemplate struct {
	ID                int
	Race              string
	StrengthMod       float32
	ConstitutionMod   float32
	IntelligenceMod   float32
	DexterityMod      float32
	AxeMod            float32
	DaggerMod         float32
	UnarmedMod        float32
	HammerMod         float32
	PolearmMod        float32
	SpearMod          float32
	StaffMod          float32
	SwordMod          float32
	ArcheryMod        float32
	CrossbowMod       float32
	SlingMod          float32
	ThrownMod         float32
	ArmorMod          float32
	DualweaponMod     float32
	ShieldMod         float32
	BardicMod         float32
	ConjuringMod      float32
	DruidicMod        float32
	IllusionMod       float32
	NecromancyMod     float32
	SorceryMod        float32
	ShamanicMod       float32
	SpellcraftMod     float32
	SummoningMod      float32
	FocusMod          float32
	ArmorsmithingMod  float32
	TailoringMod      float32
	FletchingMod      float32
	WeaponsmithingMod float32
	AlchemyMod        float32
	LapidaryMod       float32
	CalligraphyMod    float32
	EnchantingMod     float32
	HerbalismMod      float32
	HuntingMod        float32
	MiningMod         float32
	BargainingMod     float32
	CampingMod        float32
	FirstaidMod       float32
	LoreMod           float32
	PicklocksMod      float32
	ScoutingMod       float32
	SearchMod         float32
	StealthMod        float32
	TrapsMod          float32
	AeolandisMod      float32
	HieroformMod      float32
	HighgundisMod     float32
	OldpraxicMod      float32
	PraxicMod         float32
	RunicMod          float32
	Description       string
}

// ProfessionTemplate is a struct that contains all of the relevant information for how profession modifiers are defined in the game.
type ProfessionTemplate struct {
	ID                int
	Profession        string
	Hppl              int
	Mppl              int
	StrengthMod       float32
	ConstitutionMod   float32
	IntelligenceMod   float32
	DexterityMod      float32
	AxeMod            float32
	DaggerMod         float32
	UnarmedMod        float32
	HammerMod         float32
	PolearmMod        float32
	SpearMod          float32
	StaffMod          float32
	SwordMod          float32
	ArcheryMod        float32
	CrossbowMod       float32
	SlingMod          float32
	ThrownMod         float32
	ArmorMod          float32
	DualweaponMod     float32
	ShieldMod         float32
	BardicMod         float32
	ConjuringMod      float32
	DruidicMod        float32
	IllusionMod       float32
	NecromancyMod     float32
	SorceryMod        float32
	ShamanicMod       float32
	SpellcraftMod     float32
	SummoningMod      float32
	FocusMod          float32
	ArmorsmithingMod  float32
	TailoringMod      float32
	FletchingMod      float32
	WeaponsmithingMod float32
	AlchemyMod        float32
	LapidaryMod       float32
	CalligraphyMod    float32
	EnchantingMod     float32
	HerbalismMod      float32
	HuntingMod        float32
	MiningMod         float32
	BargainingMod     float32
	CampingMod        float32
	FirstaidMod       float32
	LoreMod           float32
	PicklocksMod      float32
	ScoutingMod       float32
	SearchMod         float32
	StealthMod        float32
	TrapsMod          float32
	AeolandisMod      float32
	HieroformMod      float32
	HighgundisMod     float32
	OldpraxicMod      float32
	PraxicMod         float32
	RunicMod          float32
	SkillMulti1       bool
	SkillNames1       string
	SkillValue1       float32
	SkillMulti2       bool
	SkillNames2       string
	SkillValue2       float32
	SkillMulti3       bool
	SkillNames3       string
	SkillValue3       float32
	SkillMulti4       bool
	SkillNames4       string
	SkillValue4       float32
	SkillMulti5       bool
	SkillNames5       string
	SkillValue5       float32
	Description       string
}

// MakePlayer is the meaty function we will use to validate new players being created.  It should reject requests that are not allowed by game rules.
func MakePlayer(fname string, lname string, gender string, race string, skin string) Pc {
	return Pc{
		ID:             0,
		AccountID:      0,
		Firstname:      fname,
		Lastname:       lname,
		Guild:          "Gremlins",
		Race:           race,
		Gender:         gender,
		Face:           "White",
		Skin:           skin,
		Profession:     "Engineer",
		Alive:          true,
		Plevel:         51,
		Dp:             12000,
		Hp:             450,
		Maxhp:          450,
		Bp:             250,
		Maxbp:          250,
		Mp:             300,
		Maxmp:          300,
		Sp:             150,
		Maxsp:          150,
		Strength:       65,
		Constitution:   45,
		Intelligence:   50,
		Dexterity:      50,
		Axe:            0,
		Dagger:         0,
		Unarmed:        499,
		Hammer:         0,
		Polearm:        0,
		Spear:          0,
		Staff:          0,
		Sword:          0,
		Archery:        0,
		Crossbow:       0,
		Sling:          0,
		Thrown:         0,
		Armor:          300,
		Dualweapon:     499,
		Shield:         0,
		Bardic:         0,
		Conjuring:      0,
		Druidic:        0,
		Illusion:       0,
		Necromancy:     0,
		Sorcery:        0,
		Shamanic:       0,
		Spellcraft:     0,
		Summoning:      0,
		Focus:          0,
		Armorsmithing:  0,
		Tailoring:      0,
		Fletching:      0,
		Weaponsmithing: 0,
		Alchemy:        0,
		Lapidary:       0,
		Calligraphy:    0,
		Enchanting:     0,
		Herbalism:      0,
		Hunting:        0,
		Mining:         0,
		Bargaining:     0,
		Camping:        0,
		Firstaid:       0,
		Lore:           0,
		Picklocks:      0,
		Scouting:       0,
		Search:         0,
		Stealth:        0,
		Traps:          0,
		Aeolandis:      0,
		Hieroform:      0,
		Highgundis:     0,
		Oldpraxic:      100,
		Praxic:         100,
		Runic:          0,
		Head:           "None",
		Chest:          "None",
		Arms:           "None",
		Hands:          "None",
		Legs:           "None",
		Feet:           "None",
		Cloak:          "None",
		Necklace:       "None",
		Ringone:        "None",
		Ringtwo:        "None",
		Righthand:      "None",
		Lefthand:       "None",
		Zone:           "Iskirrian Plains",
		X:              0,
		Y:              0,
		Z:              0,
		Direction:      47.3,
	}
}

// MakePlayerByName is a test function for MakePlayer().
func MakePlayerByName(name string) Pc {
	return Pc{
		ID:             0,
		AccountID:      0,
		Firstname:      name,
		Lastname:       "Mc" + name + "face",
		Guild:          "Gremlins",
		Race:           "Human",
		Gender:         "Male",
		Face:           "White",
		Skin:           "White",
		Profession:     "Engineer",
		Alive:          true,
		Plevel:         51,
		Dp:             12000,
		Hp:             450,
		Maxhp:          450,
		Bp:             250,
		Maxbp:          250,
		Mp:             300,
		Maxmp:          300,
		Sp:             150,
		Maxsp:          150,
		Strength:       65,
		Constitution:   45,
		Intelligence:   50,
		Dexterity:      50,
		Axe:            0,
		Dagger:         0,
		Unarmed:        499,
		Hammer:         0,
		Polearm:        0,
		Spear:          0,
		Staff:          0,
		Sword:          0,
		Archery:        0,
		Crossbow:       0,
		Sling:          0,
		Thrown:         0,
		Armor:          300,
		Dualweapon:     499,
		Shield:         0,
		Bardic:         0,
		Conjuring:      0,
		Druidic:        0,
		Illusion:       0,
		Necromancy:     0,
		Sorcery:        0,
		Shamanic:       0,
		Spellcraft:     0,
		Summoning:      0,
		Focus:          0,
		Armorsmithing:  0,
		Tailoring:      0,
		Fletching:      0,
		Weaponsmithing: 0,
		Alchemy:        0,
		Lapidary:       0,
		Calligraphy:    0,
		Enchanting:     0,
		Herbalism:      0,
		Hunting:        0,
		Mining:         0,
		Bargaining:     0,
		Camping:        0,
		Firstaid:       0,
		Lore:           0,
		Picklocks:      0,
		Scouting:       0,
		Search:         0,
		Stealth:        0,
		Traps:          0,
		Aeolandis:      0,
		Hieroform:      0,
		Highgundis:     0,
		Oldpraxic:      100,
		Praxic:         100,
		Runic:          0,
		Head:           "None",
		Chest:          "None",
		Arms:           "None",
		Hands:          "None",
		Legs:           "None",
		Feet:           "None",
		Cloak:          "None",
		Necklace:       "None",
		Ringone:        "None",
		Ringtwo:        "None",
		Righthand:      "None",
		Lefthand:       "None",
		Zone:           "Iskirrian Plains",
		X:              0,
		Y:              0,
		Z:              0,
		Direction:      47.3,
	}
}
